// flow-typed signature: e90a38bef94fb0fcfebcb1bf4a21c7d1
// flow-typed version: <<STUB>>/redux-auth_v0.0.5-beta5/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-auth/bootstrap-theme' {
  declare module.exports: any;
}

declare module 'redux-auth/default-theme' {
  declare module.exports: any;
}

declare module 'redux-auth/material-ui-theme' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/authenticate' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/configure' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/destroy-account' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/email-sign-in' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/email-sign-up' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/oauth-sign-in' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/request-password-reset' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/server' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/sign-out' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/ui' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/update-password-modal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/actions/update-password' {
  declare module.exports: any;
}

declare module 'redux-auth/src/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/authenticate' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/configure' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/destroy-account' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/email-sign-in' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/email-sign-up' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/oauth-sign-in' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/request-password-reset' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/server' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/sign-out' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/ui' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/update-password-modal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/update-password' {
  declare module.exports: any;
}

declare module 'redux-auth/src/reducers/user' {
  declare module.exports: any;
}

declare module 'redux-auth/src/utils/client-settings' {
  declare module.exports: any;
}

declare module 'redux-auth/src/utils/constants' {
  declare module.exports: any;
}

declare module 'redux-auth/src/utils/fetch' {
  declare module.exports: any;
}

declare module 'redux-auth/src/utils/handle-fetch-response' {
  declare module.exports: any;
}

declare module 'redux-auth/src/utils/parse-endpoint-config' {
  declare module.exports: any;
}

declare module 'redux-auth/src/utils/parse-url' {
  declare module.exports: any;
}

declare module 'redux-auth/src/utils/popup' {
  declare module.exports: any;
}

declare module 'redux-auth/src/utils/session-storage' {
  declare module.exports: any;
}

declare module 'redux-auth/src/utils/verify-auth' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/AuthGlobals' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/ButtonLoader' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/DestroyAccountButton' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/EmailSignInForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/EmailSignUpForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/ErrorList' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/Input' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/DestroyAccountErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/DestroyAccountSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/EmailSignInErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/EmailSignInSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/EmailSignUpErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/EmailSignUpSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/FirstTimeLoginErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/FirstTimeLoginSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/Modal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/OAuthSignInErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/OAuthSignInSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/PasswordResetSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/RequestPasswordResetErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/RequestPasswordResetSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/SignOutErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/SignOutSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/UpdatePasswordErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/modals/UpdatePasswordSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/OAuthSignInButton' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/RequestPasswordResetForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/SignOutButton' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/bootstrap/UpdatePasswordForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/AuthGlobals' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/ButtonLoader' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/DestroyAccountButton' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/EmailSignInForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/EmailSignUpForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/ErrorList' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/Input' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/DestroyAccountErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/DestroyAccountSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/EmailSignInErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/EmailSignInSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/EmailSignUpErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/EmailSignUpSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/FirstTimeLoginErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/FirstTimeLoginSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/Modal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/OAuthSignInErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/OAuthSignInSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/PasswordResetSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/RequestPasswordResetErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/RequestPasswordResetSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/SignOutErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/SignOutSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/UpdatePasswordErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/modals/UpdatePasswordSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/OAuthSignInButton' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/RequestPasswordResetForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/SignOutButton' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/default/UpdatePasswordForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/AuthGlobals' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/ButtonLoader' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/DestroyAccountButton' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/EmailSignInForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/EmailSignUpForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/ErrorList' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/index' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/Input' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/DestroyAccountErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/DestroyAccountSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/EmailSignInErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/EmailSignInSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/EmailSignUpErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/EmailSignUpSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/FirstTimeLoginErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/FirstTimeLoginSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/Modal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/OAuthSignInErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/OAuthSignInSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/PasswordResetSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/RequestPasswordResetErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/RequestPasswordResetSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/SignOutErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/SignOutSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/UpdatePasswordErrorModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/modals/UpdatePasswordSuccessModal' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/OAuthSignInButton' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/RequestPasswordResetForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/SignOutButton' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/material-ui/UpdatePasswordForm' {
  declare module.exports: any;
}

declare module 'redux-auth/src/views/TokenBridge' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-auth/bootstrap-theme.js' {
  declare module.exports: $Exports<'redux-auth/bootstrap-theme'>;
}
declare module 'redux-auth/default-theme.js' {
  declare module.exports: $Exports<'redux-auth/default-theme'>;
}
declare module 'redux-auth/index' {
  declare module.exports: $Exports<'redux-auth'>;
}
declare module 'redux-auth/index.js' {
  declare module.exports: $Exports<'redux-auth'>;
}
declare module 'redux-auth/material-ui-theme.js' {
  declare module.exports: $Exports<'redux-auth/material-ui-theme'>;
}
declare module 'redux-auth/src/actions/authenticate.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/authenticate'>;
}
declare module 'redux-auth/src/actions/configure.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/configure'>;
}
declare module 'redux-auth/src/actions/destroy-account.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/destroy-account'>;
}
declare module 'redux-auth/src/actions/email-sign-in.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/email-sign-in'>;
}
declare module 'redux-auth/src/actions/email-sign-up.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/email-sign-up'>;
}
declare module 'redux-auth/src/actions/oauth-sign-in.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/oauth-sign-in'>;
}
declare module 'redux-auth/src/actions/request-password-reset.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/request-password-reset'>;
}
declare module 'redux-auth/src/actions/server.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/server'>;
}
declare module 'redux-auth/src/actions/sign-out.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/sign-out'>;
}
declare module 'redux-auth/src/actions/ui.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/ui'>;
}
declare module 'redux-auth/src/actions/update-password-modal.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/update-password-modal'>;
}
declare module 'redux-auth/src/actions/update-password.js' {
  declare module.exports: $Exports<'redux-auth/src/actions/update-password'>;
}
declare module 'redux-auth/src/index.js' {
  declare module.exports: $Exports<'redux-auth/src/index'>;
}
declare module 'redux-auth/src/reducers/authenticate.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/authenticate'>;
}
declare module 'redux-auth/src/reducers/configure.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/configure'>;
}
declare module 'redux-auth/src/reducers/destroy-account.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/destroy-account'>;
}
declare module 'redux-auth/src/reducers/email-sign-in.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/email-sign-in'>;
}
declare module 'redux-auth/src/reducers/email-sign-up.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/email-sign-up'>;
}
declare module 'redux-auth/src/reducers/oauth-sign-in.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/oauth-sign-in'>;
}
declare module 'redux-auth/src/reducers/request-password-reset.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/request-password-reset'>;
}
declare module 'redux-auth/src/reducers/server.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/server'>;
}
declare module 'redux-auth/src/reducers/sign-out.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/sign-out'>;
}
declare module 'redux-auth/src/reducers/ui.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/ui'>;
}
declare module 'redux-auth/src/reducers/update-password-modal.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/update-password-modal'>;
}
declare module 'redux-auth/src/reducers/update-password.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/update-password'>;
}
declare module 'redux-auth/src/reducers/user.js' {
  declare module.exports: $Exports<'redux-auth/src/reducers/user'>;
}
declare module 'redux-auth/src/utils/client-settings.js' {
  declare module.exports: $Exports<'redux-auth/src/utils/client-settings'>;
}
declare module 'redux-auth/src/utils/constants.js' {
  declare module.exports: $Exports<'redux-auth/src/utils/constants'>;
}
declare module 'redux-auth/src/utils/fetch.js' {
  declare module.exports: $Exports<'redux-auth/src/utils/fetch'>;
}
declare module 'redux-auth/src/utils/handle-fetch-response.js' {
  declare module.exports: $Exports<'redux-auth/src/utils/handle-fetch-response'>;
}
declare module 'redux-auth/src/utils/parse-endpoint-config.js' {
  declare module.exports: $Exports<'redux-auth/src/utils/parse-endpoint-config'>;
}
declare module 'redux-auth/src/utils/parse-url.js' {
  declare module.exports: $Exports<'redux-auth/src/utils/parse-url'>;
}
declare module 'redux-auth/src/utils/popup.js' {
  declare module.exports: $Exports<'redux-auth/src/utils/popup'>;
}
declare module 'redux-auth/src/utils/session-storage.js' {
  declare module.exports: $Exports<'redux-auth/src/utils/session-storage'>;
}
declare module 'redux-auth/src/utils/verify-auth.js' {
  declare module.exports: $Exports<'redux-auth/src/utils/verify-auth'>;
}
declare module 'redux-auth/src/views/bootstrap/AuthGlobals.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/AuthGlobals'>;
}
declare module 'redux-auth/src/views/bootstrap/ButtonLoader.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/ButtonLoader'>;
}
declare module 'redux-auth/src/views/bootstrap/DestroyAccountButton.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/DestroyAccountButton'>;
}
declare module 'redux-auth/src/views/bootstrap/EmailSignInForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/EmailSignInForm'>;
}
declare module 'redux-auth/src/views/bootstrap/EmailSignUpForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/EmailSignUpForm'>;
}
declare module 'redux-auth/src/views/bootstrap/ErrorList.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/ErrorList'>;
}
declare module 'redux-auth/src/views/bootstrap/index.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/index'>;
}
declare module 'redux-auth/src/views/bootstrap/Input.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/Input'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/DestroyAccountErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/DestroyAccountErrorModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/DestroyAccountSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/DestroyAccountSuccessModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/EmailSignInErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/EmailSignInErrorModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/EmailSignInSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/EmailSignInSuccessModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/EmailSignUpErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/EmailSignUpErrorModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/EmailSignUpSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/EmailSignUpSuccessModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/FirstTimeLoginErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/FirstTimeLoginErrorModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/FirstTimeLoginSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/FirstTimeLoginSuccessModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/Modal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/Modal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/OAuthSignInErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/OAuthSignInErrorModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/OAuthSignInSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/OAuthSignInSuccessModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/PasswordResetSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/PasswordResetSuccessModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/RequestPasswordResetErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/RequestPasswordResetErrorModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/RequestPasswordResetSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/RequestPasswordResetSuccessModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/SignOutErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/SignOutErrorModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/SignOutSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/SignOutSuccessModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/UpdatePasswordErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/UpdatePasswordErrorModal'>;
}
declare module 'redux-auth/src/views/bootstrap/modals/UpdatePasswordSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/modals/UpdatePasswordSuccessModal'>;
}
declare module 'redux-auth/src/views/bootstrap/OAuthSignInButton.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/OAuthSignInButton'>;
}
declare module 'redux-auth/src/views/bootstrap/RequestPasswordResetForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/RequestPasswordResetForm'>;
}
declare module 'redux-auth/src/views/bootstrap/SignOutButton.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/SignOutButton'>;
}
declare module 'redux-auth/src/views/bootstrap/UpdatePasswordForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/bootstrap/UpdatePasswordForm'>;
}
declare module 'redux-auth/src/views/default/AuthGlobals.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/AuthGlobals'>;
}
declare module 'redux-auth/src/views/default/ButtonLoader.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/ButtonLoader'>;
}
declare module 'redux-auth/src/views/default/DestroyAccountButton.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/DestroyAccountButton'>;
}
declare module 'redux-auth/src/views/default/EmailSignInForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/EmailSignInForm'>;
}
declare module 'redux-auth/src/views/default/EmailSignUpForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/EmailSignUpForm'>;
}
declare module 'redux-auth/src/views/default/ErrorList.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/ErrorList'>;
}
declare module 'redux-auth/src/views/default/index.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/index'>;
}
declare module 'redux-auth/src/views/default/Input.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/Input'>;
}
declare module 'redux-auth/src/views/default/modals/DestroyAccountErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/DestroyAccountErrorModal'>;
}
declare module 'redux-auth/src/views/default/modals/DestroyAccountSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/DestroyAccountSuccessModal'>;
}
declare module 'redux-auth/src/views/default/modals/EmailSignInErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/EmailSignInErrorModal'>;
}
declare module 'redux-auth/src/views/default/modals/EmailSignInSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/EmailSignInSuccessModal'>;
}
declare module 'redux-auth/src/views/default/modals/EmailSignUpErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/EmailSignUpErrorModal'>;
}
declare module 'redux-auth/src/views/default/modals/EmailSignUpSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/EmailSignUpSuccessModal'>;
}
declare module 'redux-auth/src/views/default/modals/FirstTimeLoginErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/FirstTimeLoginErrorModal'>;
}
declare module 'redux-auth/src/views/default/modals/FirstTimeLoginSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/FirstTimeLoginSuccessModal'>;
}
declare module 'redux-auth/src/views/default/modals/Modal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/Modal'>;
}
declare module 'redux-auth/src/views/default/modals/OAuthSignInErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/OAuthSignInErrorModal'>;
}
declare module 'redux-auth/src/views/default/modals/OAuthSignInSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/OAuthSignInSuccessModal'>;
}
declare module 'redux-auth/src/views/default/modals/PasswordResetSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/PasswordResetSuccessModal'>;
}
declare module 'redux-auth/src/views/default/modals/RequestPasswordResetErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/RequestPasswordResetErrorModal'>;
}
declare module 'redux-auth/src/views/default/modals/RequestPasswordResetSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/RequestPasswordResetSuccessModal'>;
}
declare module 'redux-auth/src/views/default/modals/SignOutErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/SignOutErrorModal'>;
}
declare module 'redux-auth/src/views/default/modals/SignOutSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/SignOutSuccessModal'>;
}
declare module 'redux-auth/src/views/default/modals/UpdatePasswordErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/UpdatePasswordErrorModal'>;
}
declare module 'redux-auth/src/views/default/modals/UpdatePasswordSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/modals/UpdatePasswordSuccessModal'>;
}
declare module 'redux-auth/src/views/default/OAuthSignInButton.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/OAuthSignInButton'>;
}
declare module 'redux-auth/src/views/default/RequestPasswordResetForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/RequestPasswordResetForm'>;
}
declare module 'redux-auth/src/views/default/SignOutButton.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/SignOutButton'>;
}
declare module 'redux-auth/src/views/default/UpdatePasswordForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/default/UpdatePasswordForm'>;
}
declare module 'redux-auth/src/views/material-ui/AuthGlobals.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/AuthGlobals'>;
}
declare module 'redux-auth/src/views/material-ui/ButtonLoader.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/ButtonLoader'>;
}
declare module 'redux-auth/src/views/material-ui/DestroyAccountButton.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/DestroyAccountButton'>;
}
declare module 'redux-auth/src/views/material-ui/EmailSignInForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/EmailSignInForm'>;
}
declare module 'redux-auth/src/views/material-ui/EmailSignUpForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/EmailSignUpForm'>;
}
declare module 'redux-auth/src/views/material-ui/ErrorList.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/ErrorList'>;
}
declare module 'redux-auth/src/views/material-ui/index.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/index'>;
}
declare module 'redux-auth/src/views/material-ui/Input.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/Input'>;
}
declare module 'redux-auth/src/views/material-ui/modals/DestroyAccountErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/DestroyAccountErrorModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/DestroyAccountSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/DestroyAccountSuccessModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/EmailSignInErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/EmailSignInErrorModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/EmailSignInSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/EmailSignInSuccessModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/EmailSignUpErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/EmailSignUpErrorModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/EmailSignUpSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/EmailSignUpSuccessModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/FirstTimeLoginErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/FirstTimeLoginErrorModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/FirstTimeLoginSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/FirstTimeLoginSuccessModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/Modal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/Modal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/OAuthSignInErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/OAuthSignInErrorModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/OAuthSignInSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/OAuthSignInSuccessModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/PasswordResetSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/PasswordResetSuccessModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/RequestPasswordResetErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/RequestPasswordResetErrorModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/RequestPasswordResetSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/RequestPasswordResetSuccessModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/SignOutErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/SignOutErrorModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/SignOutSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/SignOutSuccessModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/UpdatePasswordErrorModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/UpdatePasswordErrorModal'>;
}
declare module 'redux-auth/src/views/material-ui/modals/UpdatePasswordSuccessModal.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/modals/UpdatePasswordSuccessModal'>;
}
declare module 'redux-auth/src/views/material-ui/OAuthSignInButton.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/OAuthSignInButton'>;
}
declare module 'redux-auth/src/views/material-ui/RequestPasswordResetForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/RequestPasswordResetForm'>;
}
declare module 'redux-auth/src/views/material-ui/SignOutButton.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/SignOutButton'>;
}
declare module 'redux-auth/src/views/material-ui/UpdatePasswordForm.js' {
  declare module.exports: $Exports<'redux-auth/src/views/material-ui/UpdatePasswordForm'>;
}
declare module 'redux-auth/src/views/TokenBridge.js' {
  declare module.exports: $Exports<'redux-auth/src/views/TokenBridge'>;
}
